### ISSUE TITLE
Собрать данные по компаниям в строительстве и превратить их в открытые данные из реестра НОСТРОЙ

### ISSUE THREAD

**Issue by ivbeg** [infoculture/scrapetasks#3]
## Цель

На портале reestr.nostroy.ru размещены общедоступные данные реестра СРО в строительстве и реестра строительных компаний участников СРО
Необходимо собрать данные по СРО и по участникам СРО и опубликовать их как открытые данные

## Задача
- выбрать язык программирования Python / R или иной, на выбор
- написать парсер для сайта reestr.nostroy.ru
- выгрузить все данные в формате CSV или JSON или XML
- загрузить набор данных на github и на хаб открытых данных hubofdata.ru

## Требования
- открытый исходный код в Github под свободной лицензией
- открытые данные под лицензией Creative Commons

## Пожелания
- сделать описание к выгруженным данным. Структуры данных и набора целиком. 

## Оценки трудоёмкости
Ожидаемое время на задачу не более 4 чсов

## Примечание
Необходимые данные из реестра СРО:
- Рег. номер 
- Полное наименование 
- Сокращенное наименование
- Адрес местонахождения
- Федеральный округ 
- ИНН
- ОГРН
- E-mail
- Адрес сайта
- Телефон
- Руководитель коллегиального органа СРО
- Руководитель исполнительного органа СРО
- Статус

Необходимые данные из реестра участников СРО:
- СРО
- Тип члена СРО
- Полное наименование
- Сокращенное наименование
- Статус члена
- Регистрационный номер члена в реестре СРО
- Дата регистрации в реестре СРО
- Дата прекращения членства
- Основание прекращения членства
- ОГРН
- ИНН
- Дата государственной регистрации
- Номер контактного телефона
- Адрес местонахождения юридического лица
- ФИО, осуществляющего функции единоличного исполнительного органа юридического лица и (или) руководителя коллегиального исполнительного органа юридического лица
- Сведения о соответствии члена СРО условиям членства в СРО, предусмотренным - законодательством РФ и (или) внутренними документами СРО
- Размер взноса в компенсационный фонд СРО
- Обновлено

А также по аналогичной логике для всех участников СРО необходимо собрать данные из вкладок "Свидетельства о допуске", "Страхование", "Проверки". 

## Вопросы
Вопросы можно писать на ibegtin@infoculture.ru или в комментариях к этой задаче

**Comment by alexFilim** [comment]
Добрый вечер, Иван,

актуальна ли еще задача?
У меня есть прототип, который выполняет часть задания. Написано на Python.
Сейчас скрипт выводит в консоль все из таблицы СРО.
Пример тут:
https://github.com/iGeophysix/sro/blob/master/main.py
Если все хорошо, то я продолжу и допишу оставшуюся часть.

**Comment by ivbeg** [comment]
Добрый вечер! Именно вот эта задача уже не актуальна, несколько решений прислали.

**Comment by leprick0n** [comment]
> Добрый вечер! Именно вот эта задача уже не актуальна, несколько решений прислали.

тоже ищу примеры решений не смог найти (
